export type Challenge = {
  id: number
  word: string
  tip: string
}

export const WORDS: Challenge[] = [
  { id: 1, word: "CSS", tip: "Styling language for web pages" },
  { id: 2, word: "REACT", tip: "JavaScript library for building UIs" },
  { id: 3, word: "HTML", tip: "Markup language for the web" },
  { id: 4, word: "JAVASCRIPT", tip: "Popular programming language" },
  { id: 5, word: "TYPESCRIPT", tip: "Adds static typing to JavaScript" },

  { id: 6, word: "PYTHON", tip: "Easy-to-read programming language" },
  { id: 7, word: "NODE", tip: "JavaScript runtime environment" },
  { id: 8, word: "GITHUB", tip: "Platform for hosting code" },
  { id: 9, word: "LINUX", tip: "Open-source operating system" },
  { id: 10, word: "DOCKER", tip: "Containerization tool" },

  { id: 11, word: "KUBERNETES", tip: "Container orchestration system" },
  { id: 12, word: "API", tip: "Interface for communication between systems" },
  { id: 13, word: "DATABASE", tip: "Stores structured information" },
  { id: 14, word: "ALGORITHM", tip: "Step-by-step instructions" },
  { id: 15, word: "VARIABLE", tip: "Stores a value in programming" },

  { id: 16, word: "FUNCTION", tip: "Reusable block of code" },
  { id: 17, word: "COMPILER", tip: "Translates code into machine language" },
  { id: 18, word: "BROWSER", tip: "Software to navigate the web" },
  { id: 19, word: "SERVER", tip: "Provides resources to clients" },
  { id: 20, word: "CLIENT", tip: "Requests resources from a server" },

  { id: 21, word: "ATOM", tip: "Basic unit of matter" },
  { id: 22, word: "GRAVITY", tip: "Force that attracts objects" },
  { id: 23, word: "ENERGY", tip: "Ability to do work" },
  { id: 24, word: "EVOLUTION", tip: "Biological change over time" },
  { id: 25, word: "GALAXY", tip: "Massive system of stars" },

  { id: 26, word: "PLANET", tip: "Orbits a star" },
  { id: 27, word: "MOLECULE", tip: "Group of bonded atoms" },
  { id: 28, word: "CHEMISTRY", tip: "Study of matter" },
  { id: 29, word: "BIOLOGY", tip: "Study of living organisms" },
  { id: 30, word: "PHYSICS", tip: "Study of matter and energy" },

  { id: 31, word: "BRAZIL", tip: "Largest country in South America" },
  { id: 32, word: "CANADA", tip: "Country known for cold weather" },
  { id: 33, word: "JAPAN", tip: "Land of the rising sun" },
  { id: 34, word: "FRANCE", tip: "Home of the Eiffel Tower" },
  { id: 35, word: "ITALY", tip: "Country shaped like a boot" },

  { id: 36, word: "GERMANY", tip: "Known for engineering" },
  { id: 37, word: "INDIA", tip: "Second most populous country" },
  { id: 38, word: "CHINA", tip: "Most populous country" },
  { id: 39, word: "EGYPT", tip: "Land of the pyramids" },
  { id: 40, word: "AUSTRALIA", tip: "Country and continent" },

  { id: 41, word: "DOG", tip: "Human's best friend" },
  { id: 42, word: "CAT", tip: "Independent furry pet" },
  { id: 43, word: "ELEPHANT", tip: "Largest land animal" },
  { id: 44, word: "TIGER", tip: "Striped predator" },
  { id: 45, word: "LION", tip: "King of the jungle" },

  { id: 46, word: "MONKEY", tip: "Climbs trees" },
  { id: 47, word: "DOLPHIN", tip: "Intelligent sea mammal" },
  { id: 48, word: "SHARK", tip: "Predator of the ocean" },
  { id: 49, word: "EAGLE", tip: "Symbol of freedom" },
  { id: 50, word: "PENGUIN", tip: "Bird that cannot fly" },

  { id: 51, word: "INCEPTION", tip: "Dream within a dream" },
  { id: 52, word: "AVATAR", tip: "Blue alien world" },
  { id: 53, word: "TITANIC", tip: "Famous ship disaster" },
  { id: 54, word: "GLADIATOR", tip: "Roman warrior film" },
  { id: 55, word: "INTERSTELLAR", tip: "Space and time exploration" },

  { id: 56, word: "MATRIX", tip: "Simulation reality" },
  { id: 57, word: "JOKER", tip: "Clown-faced villain" },
  { id: 58, word: "BATMAN", tip: "Dark knight hero" },
  { id: 59, word: "SPIDERMAN", tip: "Web-slinging hero" },
  { id: 60, word: "AVENGERS", tip: "Team of superheroes" },

  { id: 61, word: "MARIO", tip: "Famous plumber" },
  { id: 62, word: "ZELDA", tip: "Legendary adventure series" },
  { id: 63, word: "MINECRAFT", tip: "Block-building game" },
  { id: 64, word: "FORTNITE", tip: "Battle royale shooter" },
  { id: 65, word: "HALO", tip: "Sci-fi FPS series" },

  { id: 66, word: "PORTAL", tip: "Puzzle game with portals" },
  { id: 67, word: "POKEMON", tip: "Catch them all" },
  { id: 68, word: "SONIC", tip: "Fast blue hedgehog" },
  { id: 69, word: "OVERWATCH", tip: "Team-based shooter" },
  { id: 70, word: "DIABLO", tip: "Dark action RPG" },

  { id: 71, word: "PHONE", tip: "Device for communication" },
  { id: 72, word: "LAPTOP", tip: "Portable computer" },
  { id: 73, word: "TABLE", tip: "Furniture with legs" },
  { id: 74, word: "CHAIR", tip: "You sit on it" },
  { id: 75, word: "CAR", tip: "Four-wheeled vehicle" },

  { id: 76, word: "BICYCLE", tip: "Two-wheeled transport" },
  { id: 77, word: "CAMERA", tip: "Captures photos" },
  { id: 78, word: "KEYBOARD", tip: "Input device with keys" },
  { id: 79, word: "HEADPHONES", tip: "Used to listen to audio" },
  { id: 80, word: "BACKPACK", tip: "Carries items on your back" },

  { id: 81, word: "RUN", tip: "Move fast on foot" },
  { id: 82, word: "JUMP", tip: "Leap into the air" },
  { id: 83, word: "WRITE", tip: "Put words on paper" },
  { id: 84, word: "READ", tip: "Interpret text" },
  { id: 85, word: "SING", tip: "Produce musical sounds" },

  { id: 86, word: "DANCE", tip: "Move rhythmically" },
  { id: 87, word: "SWIM", tip: "Move through water" },
  { id: 88, word: "DRIVE", tip: "Operate a vehicle" },
  { id: 89, word: "COOK", tip: "Prepare food" },
  { id: 90, word: "DRAW", tip: "Create images" },

  { id: 91, word: "HAPPY", tip: "Feeling joy" },
  { id: 92, word: "SAD", tip: "Feeling sorrow" },
  { id: 93, word: "FAST", tip: "High speed" },
  { id: 94, word: "SLOW", tip: "Low speed" },
  { id: 95, word: "STRONG", tip: "Great physical power" },

  { id: 96, word: "WEAK", tip: "Lacking strength" },
  { id: 97, word: "BRIGHT", tip: "Full of light" },
  { id: 98, word: "DARK", tip: "Little or no light" },
  { id: 99, word: "LOUD", tip: "High volume" },
  { id: 100, word: "QUIET", tip: "Low volume" },
  { id: 101, word: "CLOUD", tip: "Remote servers accessed over the internet" },
  { id: 102, word: "ROBOT", tip: "Machine capable of carrying out tasks" },
  { id: 103, word: "SATELLITE", tip: "Orbits a planet" },
  { id: 104, word: "ASTRONAUT", tip: "Travels into space" },
  { id: 105, word: "TELESCOPE", tip: "Instrument to observe distant objects" },

  { id: 106, word: "MICROSCOPE", tip: "Instrument to observe tiny objects" },
  { id: 107, word: "VIRUS", tip: "Microscopic infectious agent" },
  { id: 108, word: "BACTERIA", tip: "Single-celled organism" },
  { id: 109, word: "ANTIBODY", tip: "Immune system protein" },
  { id: 110, word: "VACCINE", tip: "Provides immunity" },

  { id: 111, word: "OXYGEN", tip: "Gas essential for breathing" },
  { id: 112, word: "CARBON", tip: "Element found in all living things" },
  { id: 113, word: "HYDROGEN", tip: "Lightest element" },
  { id: 114, word: "NITROGEN", tip: "Most abundant gas in Earth's atmosphere" },
  { id: 115, word: "PLASMA", tip: "Fourth state of matter" },

  { id: 116, word: "VOLCANO", tip: "Mountain that erupts lava" },
  { id: 117, word: "EARTHQUAKE", tip: "Shaking of the ground" },
  { id: 118, word: "TSUNAMI", tip: "Large ocean wave caused by seismic activity" },
  { id: 119, word: "HURRICANE", tip: "Powerful tropical storm" },
  { id: 120, word: "TORNADO", tip: "Rotating column of air" },

  { id: 121, word: "FOREST", tip: "Large area covered with trees" },
  { id: 122, word: "DESERT", tip: "Dry region with little rainfall" },
  { id: 123, word: "OCEAN", tip: "Large body of saltwater" },
  { id: 124, word: "RIVER", tip: "Flowing body of water" },
  { id: 125, word: "MOUNTAIN", tip: "Large natural elevation" },

  { id: 126, word: "ISLAND", tip: "Land surrounded by water" },
  { id: 127, word: "VALLEY", tip: "Low area between mountains" },
  { id: 128, word: "GLACIER", tip: "Large mass of ice" },
  { id: 129, word: "CANYON", tip: "Deep gorge with steep sides" },
  { id: 130, word: "WATERFALL", tip: "Water dropping from a height" },

  { id: 131, word: "ORANGE", tip: "Citrus fruit" },
  { id: 132, word: "BANANA", tip: "Long yellow fruit" },
  { id: 133, word: "APPLE", tip: "Common red or green fruit" },
  { id: 134, word: "GRAPE", tip: "Small round fruit" },
  { id: 135, word: "STRAWBERRY", tip: "Red fruit with seeds on the outside" },

  { id: 136, word: "BROCCOLI", tip: "Green vegetable resembling a tree" },
  { id: 137, word: "CARROT", tip: "Orange root vegetable" },
  { id: 138, word: "POTATO", tip: "Common starchy vegetable" },
  { id: 139, word: "ONION", tip: "Vegetable that makes you cry" },
  { id: 140, word: "TOMATO", tip: "Red fruit often used as a vegetable" },

  { id: 141, word: "COFFEE", tip: "Popular caffeinated drink" },
  { id: 142, word: "TEA", tip: "Beverage made from leaves" },
  { id: 143, word: "JUICE", tip: "Drink made from fruit" },
  { id: 144, word: "WATER", tip: "Essential liquid for life" },
  { id: 145, word: "MILK", tip: "White nutritious drink" },

  { id: 146, word: "BREAD", tip: "Staple food made from flour" },
  { id: 147, word: "PIZZA", tip: "Flatbread with toppings" },
  { id: 148, word: "BURGER", tip: "Sandwich with a patty" },
  { id: 149, word: "PASTA", tip: "Italian noodle dish" },
  { id: 150, word: "SALAD", tip: "Mix of vegetables" },

  { id: 151, word: "ENGINE", tip: "Machine that converts energy into motion" },
  { id: 152, word: "BATTERY", tip: "Stores electrical energy" },
  { id: 153, word: "SCREEN", tip: "Displays visual output" },
  { id: 154, word: "MONITOR", tip: "Computer display" },
  { id: 155, word: "PRINTER", tip: "Produces physical copies" },

  { id: 156, word: "ROUTER", tip: "Distributes internet connection" },
  { id: 157, word: "MODEM", tip: "Connects to the internet" },
  { id: 158, word: "KEYBOARD", tip: "Input device with keys" },
  { id: 159, word: "MOUSE", tip: "Pointing device" },
  { id: 160, word: "WEBCAM", tip: "Captures video" },

  { id: 161, word: "PAINT", tip: "Colored substance used for art" },
  { id: 162, word: "BRUSH", tip: "Tool for painting" },
  { id: 163, word: "CANVAS", tip: "Surface for painting" },
  { id: 164, word: "SCULPTURE", tip: "Three-dimensional artwork" },
  { id: 165, word: "MUSEUM", tip: "Place that displays art" },

  { id: 166, word: "NOVEL", tip: "Long fictional book" },
  { id: 167, word: "POEM", tip: "Short literary composition" },
  { id: 168, word: "AUTHOR", tip: "Writes books" },
  { id: 169, word: "LIBRARY", tip: "Place with many books" },
  { id: 170, word: "CHAPTER", tip: "Section of a book" },

  { id: 171, word: "TEACHER", tip: "Educates students" },
  { id: 172, word: "STUDENT", tip: "Learns in school" },
  { id: 173, word: "CLASSROOM", tip: "Place where lessons happen" },
  { id: 174, word: "HOMEWORK", tip: "Assignments done at home" },
  { id: 175, word: "EXAM", tip: "Test of knowledge" },

  { id: 176, word: "HOSPITAL", tip: "Place for medical treatment" },
  { id: 177, word: "DOCTOR", tip: "Provides medical care" },
  { id: 178, word: "NURSE", tip: "Assists in medical care" },
  { id: 179, word: "MEDICINE", tip: "Treats illness" },
  { id: 180, word: "SURGERY", tip: "Medical operation" },

  { id: 181, word: "POLICE", tip: "Enforces the law" },
  { id: 182, word: "FIREMAN", tip: "Extinguishes fires" },
  { id: 183, word: "LAWYER", tip: "Represents clients legally" },
  { id: 184, word: "JUDGE", tip: "Presides over court cases" },
  { id: 185, word: "PRISON", tip: "Place where criminals are held" },

  { id: 186, word: "AIRPLANE", tip: "Vehicle that flies" },
  { id: 187, word: "TRAIN", tip: "Runs on tracks" },
  { id: 188, word: "BUS", tip: "Public transportation vehicle" },
  { id: 189, word: "BOAT", tip: "Vehicle that floats on water" },
  { id: 190, word: "SUBMARINE", tip: "Underwater vessel" },

  { id: 191, word: "CURRENCY", tip: "System of money" },
  { id: 192, word: "BANK", tip: "Financial institution" },
  { id: 193, word: "WALLET", tip: "Holds money" },
  { id: 194, word: "COIN", tip: "Metal form of money" },
  { id: 195, word: "CREDIT", tip: "Borrowed financial value" },

  { id: 196, word: "MARKET", tip: "Place to buy goods" },
  { id: 197, word: "STORE", tip: "Sells products" },
  { id: 198, word: "RESTAURANT", tip: "Place to eat food" },
  { id: 199, word: "HOTEL", tip: "Place to stay overnight" },
  { id: 200, word: "AIRPORT", tip: "Place where planes take off" },
  { id: 201, word: "UNIVERSE", tip: "All of space and time" },
  { id: 202, word: "COSMOS", tip: "The entire physical world" },
  { id: 203, word: "ASTEROID", tip: "Rocky object orbiting the sun" },
  { id: 204, word: "COMET", tip: "Icy body with a glowing tail" },
  { id: 205, word: "METEOR", tip: "Shooting star" },

  { id: 206, word: "BLACKHOLE", tip: "Region with extreme gravity" },
  { id: 207, word: "NEBULA", tip: "Cloud of gas and dust in space" },
  { id: 208, word: "ORBIT", tip: "Path around a celestial body" },
  { id: 209, word: "SPACECRAFT", tip: "Vehicle designed for space travel" },
  { id: 210, word: "GRAVITATION", tip: "Force pulling objects together" },

  { id: 211, word: "CIRCUIT", tip: "Path for electrical current" },
  { id: 212, word: "RESISTOR", tip: "Limits electrical flow" },
  { id: 213, word: "CAPACITOR", tip: "Stores electrical charge" },
  { id: 214, word: "TRANSISTOR", tip: "Switches or amplifies signals" },
  { id: 215, word: "MICROCHIP", tip: "Small integrated circuit" },

  { id: 216, word: "NETWORK", tip: "Connected system of computers" },
  { id: 217, word: "PROTOCOL", tip: "Rules for data communication" },
  { id: 218, word: "ENCRYPTION", tip: "Secures data through encoding" },
  { id: 219, word: "FIREWALL", tip: "Protects against unauthorized access" },
  { id: 220, word: "PASSWORD", tip: "Used for authentication" },

  { id: 221, word: "JOURNEY", tip: "Act of traveling" },
  { id: 222, word: "ADVENTURE", tip: "Exciting experience" },
  { id: 223, word: "DISCOVERY", tip: "Finding something new" },
  { id: 224, word: "TREASURE", tip: "Valuable items" },
  { id: 225, word: "MYSTERY", tip: "Something difficult to explain" },

  { id: 226, word: "CASTLE", tip: "Large fortified building" },
  { id: 227, word: "KINGDOM", tip: "Land ruled by a monarch" },
  { id: 228, word: "DRAGON", tip: "Mythical fire-breathing creature" },
  { id: 229, word: "WIZARD", tip: "Magic user" },
  { id: 230, word: "POTION", tip: "Magical liquid" },

  { id: 231, word: "HERO", tip: "Brave protagonist" },
  { id: 232, word: "VILLAIN", tip: "Main antagonist" },
  { id: 233, word: "BATTLE", tip: "Fight between opponents" },
  { id: 234, word: "QUEST", tip: "Mission or journey" },
  { id: 235, word: "LEGEND", tip: "Traditional heroic story" },

  { id: 236, word: "CULTURE", tip: "Beliefs and customs of a group" },
  { id: 237, word: "TRADITION", tip: "Long-established practice" },
  { id: 238, word: "LANGUAGE", tip: "System of communication" },
  { id: 239, word: "HISTORY", tip: "Study of past events" },
  { id: 240, word: "PHILOSOPHY", tip: "Study of knowledge and existence" },

  { id: 241, word: "ECONOMY", tip: "System of production and trade" },
  { id: 242, word: "INDUSTRY", tip: "Manufacturing sector" },
  { id: 243, word: "SCIENCE", tip: "Systematic study of the natural world" },
  { id: 244, word: "TECHNOLOGY", tip: "Application of scientific knowledge" },
  { id: 245, word: "EDUCATION", tip: "Process of learning" },

  { id: 246, word: "COMMUNITY", tip: "Group living together" },
  { id: 247, word: "FAMILY", tip: "Group related by blood or marriage" },
  { id: 248, word: "FRIENDSHIP", tip: "Bond between friends" },
  { id: 249, word: "HAPPINESS", tip: "State of joy" },
  { id: 250, word: "COURAGE", tip: "Ability to face fear" },

  { id: 251, word: "ARTIST", tip: "Creates art" },
  { id: 252, word: "MUSICIAN", tip: "Plays musical instruments" },
  { id: 253, word: "ACTOR", tip: "Performs in films or plays" },
  { id: 254, word: "DANCER", tip: "Performs dance" },
  { id: 255, word: "SINGER", tip: "Performs songs" },

  { id: 256, word: "PAINTER", tip: "Creates artwork with paint" },
  { id: 257, word: "SCIENTIST", tip: "Conducts research" },
  { id: 258, word: "ENGINEER", tip: "Designs and builds systems" },
  { id: 259, word: "PROGRAMMER", tip: "Writes code" },
  { id: 260, word: "DESIGNER", tip: "Creates visual concepts" },

  { id: 261, word: "FOREST", tip: "Large area filled with trees" },
  { id: 262, word: "JUNGLE", tip: "Dense tropical forest" },
  { id: 263, word: "SAVANNA", tip: "Grassland with scattered trees" },
  { id: 264, word: "TUNDRA", tip: "Cold treeless region" },
  { id: 265, word: "WETLAND", tip: "Area saturated with water" },

  { id: 266, word: "SUNRISE", tip: "Beginning of daylight" },
  { id: 267, word: "SUNSET", tip: "End of daylight" },
  { id: 268, word: "RAINBOW", tip: "Colored arc in the sky" },
  { id: 269, word: "THUNDER", tip: "Sound from lightning" },
  { id: 270, word: "LIGHTNING", tip: "Electric discharge in the sky" },

  { id: 271, word: "CANDLE", tip: "Wax stick that burns" },
  { id: 272, word: "LANTERN", tip: "Portable light source" },
  { id: 273, word: "FLASHLIGHT", tip: "Handheld electric light" },
  { id: 274, word: "MATCH", tip: "Small stick that ignites" },
  { id: 275, word: "FIREPLACE", tip: "Indoor place for fire" },

  { id: 276, word: "GARDEN", tip: "Area for growing plants" },
  { id: 277, word: "FLOWER", tip: "Colorful part of a plant" },
  { id: 278, word: "TREE", tip: "Tall plant with a trunk" },
  { id: 279, word: "LEAF", tip: "Green part of a plant" },
  { id: 280, word: "ROOT", tip: "Underground part of a plant" },

  { id: 281, word: "CLOTHES", tip: "Items worn on the body" },
  { id: 282, word: "SHOES", tip: "Footwear" },
  { id: 283, word: "JACKET", tip: "Outer clothing for warmth" },
  { id: 284, word: "HAT", tip: "Headwear" },
  { id: 285, word: "GLOVES", tip: "Coverings for hands" },

  { id: 286, word: "CELEBRATION", tip: "Festive event" },
  { id: 287, word: "HOLIDAY", tip: "Day of rest or festivity" },
  { id: 288, word: "BIRTHDAY", tip: "Anniversary of birth" },
  { id: 289, word: "FESTIVAL", tip: "Public celebration" },
  { id: 290, word: "CEREMONY", tip: "Formal event" },

  { id: 291, word: "INNOVATION", tip: "New idea or method" },
  { id: 292, word: "CREATIVITY", tip: "Ability to produce original ideas" },
  { id: 293, word: "IMAGINATION", tip: "Ability to form new ideas" },
  { id: 294, word: "INSPIRATION", tip: "Motivation to create" },
  { id: 295, word: "AMBITION", tip: "Strong desire to achieve" },

  { id: 296, word: "BALANCE", tip: "State of stability" },
  { id: 297, word: "FOCUS", tip: "Concentration on a task" },
  { id: 298, word: "PATIENCE", tip: "Ability to wait calmly" },
  { id: 299, word: "WISDOM", tip: "Knowledge gained through experience" },
  { id: 300, word: "SUCCESS", tip: "Achievement of a goal" },

]
